CREATE TABLE `User` (userID int(10) NOT NULL AUTO_INCREMENT, RoleroleID int(10) NOT NULL, username varchar(50), email varchar(100), passwordHash varchar(256), createdAt timestamp NULL, PRIMARY KEY (userID), UNIQUE INDEX (userID));
CREATE TABLE `File` (fileID int(10) NOT NULL AUTO_INCREMENT, UseruserID int(10) NOT NULL, fileName varchar(255), fileHash varchar(64), uploadDate timestamp NULL, fileSize bigint(19), PRIMARY KEY (fileID), UNIQUE INDEX (fileID));
CREATE TABLE FileAnalysis (fileAnalysisID int(10) NOT NULL AUTO_INCREMENT, FilefileID int(10) NOT NULL, fileStatus varchar(20), fileAnalysisDate timestamp NULL, fileAnalysisResult varchar(2048), PRIMARY KEY (fileAnalysisID), UNIQUE INDEX (fileAnalysisID));
CREATE TABLE Url (urlID int(10) NOT NULL AUTO_INCREMENT, UseruserID int(10) NOT NULL, urlName varchar(2048), submitDate timestamp NULL, PRIMARY KEY (urlID), UNIQUE INDEX (urlID));
CREATE TABLE UrlAnalysis (urlAnalysisID int(10) NOT NULL AUTO_INCREMENT, UrlurlID int(10) NOT NULL, urlStatus varchar(20), urlAnalysisDate timestamp NULL, urlAnalysisResult varchar(2048), PRIMARY KEY (urlAnalysisID), UNIQUE INDEX (urlAnalysisID));
CREATE TABLE MalwareSignature (signatureID int(10) NOT NULL AUTO_INCREMENT, malwareName varchar(100), riskLevel varchar(20), malwareDesc varchar(2048), PRIMARY KEY (signatureID), UNIQUE INDEX (signatureID));
CREATE TABLE FileAnalysisMalware (FileAnalysisfileAnalysisID int(10) NOT NULL, MalwareSignaturesignatureID int(10) NOT NULL);
CREATE TABLE UrlAnalysisMalware (UrlAnalysisUrlAnalysisID int(10) NOT NULL, MalwareSignaturesignatureID int(10) NOT NULL);
CREATE TABLE Role (roleID int(10) NOT NULL AUTO_INCREMENT, roleName varchar(50), roleDesc varchar(255), PRIMARY KEY (roleID), UNIQUE INDEX (roleID));
CREATE TABLE UserSession (sessionID int(10) NOT NULL AUTO_INCREMENT, UseruserID int(10) NOT NULL, sessionToken varchar(255), sessionCreatedAt timestamp NULL, sessionExpireAt timestamp NULL, PRIMARY KEY (sessionID), UNIQUE INDEX (sessionID));
ALTER TABLE `File` ADD CONSTRAINT FKFile481978 FOREIGN KEY (UseruserID) REFERENCES `User` (userID);
ALTER TABLE FileAnalysis ADD CONSTRAINT FKFileAnalys249246 FOREIGN KEY (FilefileID) REFERENCES `File` (fileID);
ALTER TABLE FileAnalysisMalware ADD CONSTRAINT FKFileAnalys746825 FOREIGN KEY (FileAnalysisfileAnalysisID) REFERENCES FileAnalysis (fileAnalysisID);
ALTER TABLE FileAnalysisMalware ADD CONSTRAINT FKFileAnalys539236 FOREIGN KEY (MalwareSignaturesignatureID) REFERENCES MalwareSignature (signatureID);
ALTER TABLE Url ADD CONSTRAINT FKUrl586377 FOREIGN KEY (UseruserID) REFERENCES `User` (userID);
ALTER TABLE UrlAnalysis ADD CONSTRAINT FKUrlAnalysi237419 FOREIGN KEY (UrlurlID) REFERENCES Url (urlID);
ALTER TABLE UrlAnalysisMalware ADD CONSTRAINT FKUrlAnalysi674094 FOREIGN KEY (UrlAnalysisUrlAnalysisID) REFERENCES UrlAnalysis (urlAnalysisID);
ALTER TABLE UrlAnalysisMalware ADD CONSTRAINT FK_UrlAnalysisMalware_MalwareSignature FOREIGN KEY (MalwareSignaturesignatureID) REFERENCES MalwareSignature (signatureID);
ALTER TABLE UserSession ADD CONSTRAINT FKUserSessio650077 FOREIGN KEY (UseruserID) REFERENCES `User` (userID);
ALTER TABLE `User` ADD CONSTRAINT FKUser341726 FOREIGN KEY (RoleroleID) REFERENCES Role (roleID);
